### ISSUE TITLE
Unable to create blog post

### ISSUE THREAD

**Issue by guylepage3** [jay-hwang/guild-dev#4]
I am using a throw away profile and trying to create a blog post but it's not saving. However, when I click "Create Blog," I can see files are being stored and/or updated in my Dropbox.

**Comment by guylepage3** [comment]
<img width="1251" alt="screenshot 2017-07-18 17 23 52" src="https://user-images.githubusercontent.com/1711854/28340624-69ccccf6-6bde-11e7-8380-998f57adbed5.png">
<img width="1248" alt="screenshot 2017-07-18 17 24 03" src="https://user-images.githubusercontent.com/1711854/28340626-69d5be7e-6bde-11e7-889d-6a21c143b3b1.png">

**Comment by guylepage3** [comment]
From Blockstack Slack #apps

Jay Hwang [5:27 PM] 
@guylepage3 does it show when you go back to the home page?

<img width="1249" alt="screenshot 2017-07-18 17 28 35" src="https://user-images.githubusercontent.com/1711854/28340668-95e7214c-6bde-11e7-8f0b-1cc2bf9a1ef0.png">

**Comment by jay-hwang** [comment]
@guylepage3 does the throwaway account have a username by any chance? Also are you on Blockstack Browser version 11.1 or 11.0?

**Comment by jay-hwang** [comment]
Also, you can't add images yet. There's just a singe default image for all blogs

**Comment by guylepage3** [comment]
>@guylepage3 does the throwaway account have a username by any chance? Also are you on Blockstack Browser version 11.1 or 11.0?

No it does not.

**Comment by guylepage3** [comment]
>Also, you can't add images yet. There's just a singe default image for all blogs

Yeah. I tried to add an image as well but could not.

**Comment by jay-hwang** [comment]
Okay let me try it out with a throwaway account and try to figure out what's going on

**Comment by guylepage3** [comment]
any luck here @jay-hwang?

**Comment by jay-hwang** [comment]
Hey @guylepage3, sorry for the delay. I made a throwaway account and was able to replicate the issue. 

I think the issue was because I hadn't updated the blockstack version in `package.json` file to the latest version. I just updated it, tested and it worked. I just pushed to master, so pull from master and you should be able to write blogs without a username. 

Thanks for bringing this issue to light! Really appreciate it. Let me know if there are any other issues/suggestions/improvements with anything. I'll leave this issue open in case it's not actually fixed and I just think it is.

Cheers!

**Comment by guylepage3** [comment]
Awesome news @jay-hwang! 😄

I will not be able to get back to this issue until after Monday as we are on a deadline at the moment but definitely looking forward to helping out with UI. :)
